import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../../public/style/tw.css";
import "./globals.css";
import "primeicons/primeicons.css";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/tailwind-light/theme.css";
import "primeflex/primeflex.css";

// Components
import { Layout } from "@/components/client/Layout"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const language = "pt-br";
	return (
		<PrimeReactProvider value={{unstyled: true}}>
			<html lang={language} className="h-screen">
				<body className={`${inter.className}  h-full`}>
					<Layout>{children}</Layout>
				</body>
			</html>
		</PrimeReactProvider>
	);
}
